version: 2

updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: pub
    directory: /apps/employee_app
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      flutter-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
