# Generated by Django 5.2.17 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("employees", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="work_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name="employee",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="employee",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[
                    ("unspecified", "未填写"),
                    ("female", "女"),
                    ("male", "男"),
                ],
                default="unspecified",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="office_location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
