# Generated by Django 5.2.17 on 2026-08-20 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=8)),
                ('file_size', models.PositiveBigIntegerField()),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_employee_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工附件',
                'verbose_name_plural': '员工附件',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['employee', 'deleted_at', 'created_at'], name='employees_e_employe_71a480_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('file_size__gte', 1), ('file_size__lte', 10485760)), name='employee_attach_file_size_range')],
            },
        ),
    ]
