# Generated by Django 5.2.17 on 2026-08-19 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_options_alter_auditevent_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditArchiveBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('cutoff_at', models.DateTimeField()),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('archive_filename', models.CharField(blank=True, max_length=255)),
                ('manifest_filename', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('hmac_sha256', models.CharField(blank=True, max_length=64)),
                ('hmac_key_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': '审计归档批次',
                'verbose_name_plural': '审计归档批次',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'cutoff_at'], name='audit_arch_status_cut_idx')],
            },
        ),
    ]
