# Generated by Django 5.2.17 on 2026-08-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_lifecycle_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinvitation',
            name='token_key_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetchallenge',
            name='token_key_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
